### ISSUE TITLE
docker-composer cannot be up

### ISSUE THREAD

**Issue by nutnud** [steveoh/arcgis-on-docker#2]
[root@Docker docker_arcgisserver]# docker-compose up
Starting arcgis-server
Attaching to arcgis-server
arcgis-server    |  /arcgis/authorize-and-start.sh: /bin/sh^M: bad interpreter: No such file or directory

This what I got when I run docker-compose up 
I didn't change anything on your code.

**Comment by steveoh** [comment]
Start the container and look if that file exists. Otherwise make sure you have a *.prvc license file. You'll probably want to change [authorize-and-start](https://github.com/steveoh/arcgis-on-docker/blob/master/authorize-and-start.sh#L12) to use your own email address. 

Good luck. Otherwise I have no idea what could be the issue. I don't use this often, it was a proof of concept and it kinda worked on OSX. That was 2 or 3 docker release versions ago so something may have changed in there also. Please let me know what you figure and so I can update this if it is an issue with my code.
